### ISSUE TITLE
task: sorting of tables in the UI

### ISSUE THREAD

**Issue by fooelisa** [opsmill/infrahub#1508]
### Component

Frontend UI

### Task Description

we already have https://github.com/opsmill/infrahub/issues/1396 about sorting artifacts, however I had the feeling sorting would be a useful feature in many of the UI views. Maybe there's a way to build in something generic that would enable us to sort by any table field provided, for instance 
<img width="1405" alt="Screenshot 2023-11-23 at 17 15 58" src="https://github.com/opsmill/infrahub/assets/7875777/204c8d97-01b9-486f-b11e-f48cfce835be">

**Comment by pa-lem** [comment]
will be taken into account in https://github.com/opsmill/infrahub/issues/3456
