### ISSUE TITLE
feature: Be able to use Dropdown  as filters

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#1615]
### Component

Frontend UI, API Server / GraphQL, Python SDK

### Describe the Feature Request

Following the creation of Dropdown, we need to be able to use it as filter.

### Describe the Use Case

Using dropdown as a Filter via SDK and Frontend, when looking at a node

**Comment by BRBCoffeeDebuff** [comment]
Is this a duplicate of https://github.com/opsmill/infrahub/issues/2050
