### ISSUE TITLE
bug: Ancestors & Descendants not updated when adding a parent after creation on hierarchical node

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#2312]
### Component

API Server / GraphQL

### Current Behavior

When creating a hierarchical node, if you don't set the `parent` node directly but first save it and then update it, the `parent` is updated but not the ancestors list. (

### Expected Behavior

Ancestors / Descendants lists are updated

### Steps to Reproduce

Using the base schema in the main repository :

**Working :**
- Add a Country (Netherlands)
- Add a Site (Amsterdam 01) with the parent set to the new country

**Not working :**
- Add a Site (Amsterdam 02) and save
- Update the Site `parent` to the new Country

**Comment by dgarros** [comment]
I'm not able to reproduce this issue on 0.16, most likely it's been fixed already
Please reopen it if you are still seeing the issue
