### ISSUE TITLE
task: Remove RabbitMQ containers from Python SDK integration tests

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#2504]
### Component

CI/CD

### Task Description

The ./tasks folder control what containers are started as part of the tests. Of late a number of SDK Integration test jobs has failed due to containers stopping. (example: https://github.com/opsmill/infrahub/actions/runs/8156689664/job/22294846632?pr=2460) Most often it's the message-queue container that stops working. I don't think those containers are actually used within the SDK tests and we start three of them.

While I would also like to know why they are crashing (could just be that the runner for these jobs are too small and they are running out of memory), we shouldn't start them if they are not needed. Currently we're just wasting resources and and they are causing errors in the pipeline.

**Comment by dgarros** [comment]
I'm gonna close this one because we need to re-visit how to run the integration tests for the SDK after the migration to its own repository
