### ISSUE TITLE
feature: Add a button to the GraphQLQuery detailed view to easily open the query in GraphiQL

### ISSUE THREAD

**Issue by dgarros** [opsmill/infrahub#2656]
### Component

Frontend UI

### Describe the Feature Request

When viewing a GraphQLQuery object in the frontend it would be useful to have a button `Open in GraphiQL` to quickly open the query in GraphiQL (`/graphql/<branch_name>`) with the appropriate variables pre-defined.

### Describe the Use Case

Improve the user experience by reducing the number of steps required to execute a specific GraphQL query in GraphiQL

**Comment by bilalabbad** [comment]
merged
