### ISSUE TITLE
task: Update Create New Branch form with in context help descriptions 

### ISSUE THREAD

**Issue by BRBCoffeeDebuff** [opsmill/infrahub#2726]
### Component

Frontend UI

### Task Description

As a user making selections where I don't understand what that selection means makes me anxious. When creating a new branch the 'isolated mode' selection doesn't inform me of what the selection does and just as importantly doesn't tell me what the default behavior is. This needs in context help to ensure the user understands the choice to be made.

![image](https://github.com/opsmill/infrahub/assets/41315229/5feaacaf-2c29-4d9b-af44-638092d97d2f)

**Comment by bilalabbad** [comment]
not relevant anymore. I'm closing it.
