### ISSUE TITLE
task: Investigate diff and merge performance

### ISSUE THREAD

**Issue by fatih-acar** [opsmill/infrahub#2834]
### Component

API Server / GraphQL

### Task Description

According to scale tests results, the API server is CPU bound when doing fetching diff for a branch with 10k changes.
Also the branch merge mutation takes an eternity (16 minutes), due to the database?

![image](https://github.com/opsmill/infrahub/assets/15028881/56c1d24b-f404-4650-b96b-dd4cd0ea4319)

**Comment by dgarros** [comment]
The team is actively working on a new version of the diff, closing this one for now because I don't think we need more investigation right now
