### ISSUE TITLE
Table Column Filters

### ISSUE THREAD

**Issue by petercrocker** [opsmill/infrahub#2858]
## **💁‍♂️ Problem\/Context**

*As a user I may have hundreds of options in a table to select from\. I need a way to filter down to only the relevant options quickly\.* <span data-preserve-white-space></span>

<p></p>

## 🪚 Jobs to Be Done

As a user I want to:

- Filter the table by column values\. Each column should have an independent way to filter it\. <span data-preserve-white-space></span>

- Multi\-Select items in a column that I want to look at\. For example I may want to see all L3 links that start at New York, Boston, Or Philidelphia

<p></p>

<p></p>

## 🎨 Design

*Add links to design as well as any thoughts around how the design will work*

<p></p>

**Comment by pa-lem** [comment]
will be taken into account in https://github.com/opsmill/infrahub/issues/3456
