### ISSUE TITLE
bug: It's currently possible to add an IPAddress with a prefixlen > to the prefix containing it

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#3124]
### Component

API Server / GraphQL

### Current Behavior

It's currently posisble to add an ip with a prefixlen bigger than the prefix containing it

![image](https://github.com/opsmill/infrahub/assets/1334310/e124d5b0-7ac3-4463-8d7a-272869706485)

### Expected Behavior

Either we accepted the IP but we don't set it into the prefix or we refused the IP

### Steps to Reproduce

With the demo schema
- load schema
- Create a prefix
- Create several IP into this prefix

**Comment by gmazoyer** [comment]
We decided, a while ago, to keep that behaviour to stay close to what other IPAM do. Closing the issue for now. We might want to revisit this later if users find this disturbing.
