### ISSUE TITLE
bug: CI Workflow "Update Docker Compose on Pyproject update in Stable" doesn't seem to be triggered

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3276]
### Component

CI

### Current Behavior

 CI Workflow "Update Docker Compose on pyproject update in Stable" doesn't seem to have been triggered on a push to the stable branch with a modification of the pyproject.toml file.

**Comment by wvandeun** [comment]
@BeArchiTek I don't think this one is fixed?

**Comment by BeArchiTek** [comment]
Should be fix with https://github.com/opsmill/infrahub/pull/3675 and https://github.com/opsmill/infrahub/pull/3885
