### ISSUE TITLE
bug: Sidebar menu is not accessible on small screens

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#3367]
### Component

Frontend UI

### Current Behavior

If you view Infrahub on a small screen the left sidebar menu is not visible and if it's possible to expand the menu in some way I'm not able to find it.

<img width="1079" alt="Screenshot 2024-05-20 at 14 01 30" src="https://github.com/opsmill/infrahub/assets/6694669/a7845c3f-386b-44cb-9ab0-50242b017da5">

### Expected Behavior

It should always be possible to get to the sidebar even if you need to click to expand something.

**Comment by BRBCoffeeDebuff** [comment]
> Thanks @ogenstad , this is a real issue. One of the solutions is to revise the Menu sidebar. In particular, with the possibility of having a side reduction (especially for small screens). Even for larger screens, this feature is necessary for a good understanding of the display. @BRBCoffeeDebuff , shall we open a topic on the sidebar ?

Want to open up a ticket and flag it as Tech Debt @UXvsOpsMill lets chat about when we can work on this
