### ISSUE TITLE
bug: fast notification makes e2e test flaky

### ISSUE THREAD

**Issue by fatih-acar** [opsmill/infrahub#3438]
### Component

Frontend UI

### Current Behavior

[41c8bc82c273a22d78c3cc682eba145b84d67ad8.webm](https://github.com/opsmill/infrahub/assets/15028881/cc45cbee-3d54-4337-a7a5-ae45c86b7358)

As seen in the video, the test fails because we don't wait for the green popup to disappear at each creation and there is a missing green popup at the 3rd IP prefix creation which causes the test to wait forever...

### Expected Behavior

Either fix the test or implement the green popups in a way that it handles fast creations correctly.

**Comment by bilalabbad** [comment]
A lot of change were done around forms. I did not see this flaky for a while. I'll close it for now
