### ISSUE TITLE
bug: e2e test fails to fill form input

### ISSUE THREAD

**Issue by fatih-acar** [opsmill/infrahub#3439]
### Component

Frontend UI

### Current Behavior

[2946818a2e5e40a7beb1e150a5199fc800e11779.webm](https://github.com/opsmill/infrahub/assets/15028881/3852e6b9-f8af-420d-97db-a2fdae17ead0)

In the video, we can see that the test fails to fill the form value with the `11.0.0.0/10` prefix.

### Expected Behavior

Test should successfully fill the form input.

**Comment by bilalabbad** [comment]
should be fixed after https://github.com/opsmill/infrahub/pull/3653
