### ISSUE TITLE
bug: Resource Manager Default Prefix Length is unclear in terms what input is expected

### ISSUE THREAD

**Issue by BRBCoffeeDebuff** [opsmill/infrahub#3490]
### Current Behavior

Default Prefix Length is unclear in terms what input is expected. Should this be /32 or 32 or 255.255.255.0?
![image](https://github.com/opsmill/infrahub/assets/41315229/1d3ea6fb-1e1b-4b20-b125-0e8561795dd8)

### Expected Behavior

Add greyed out prefill with expected value type or (?) with explanation

**Comment by ogenstad** [comment]
The frontend should know that this is an integer. We can also add a description to the attributes in the schema, descriptions are missing at the moment.

**Comment by ogenstad** [comment]
I noticed that the frontend actually won't except input that isn't an integer here so that might at provide some guidance.

**Comment by pa-lem** [comment]
Yes, the input is of type integer (hence the arrows to go up or down) so nothing else than numbers can be typed

There is already a feature for the fields description, if provided a tooltip will be visible when hovering a "?" button, so this is just a small schema update to do here

**Comment by ogenstad** [comment]
Fixed in #3533.
