### ISSUE TITLE
feature: Add ability to create, list and delete API tokens

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#3527]
### Component

Frontend UI

### Describe the Feature Request

Currently it's not possible to create API tokens, list existing ones or delete undesired tokens from the frontend.

Tokens are defined within the Internal namespace and as such they are not exposed through the general GraphQL interface instead a logged in user would have access to these queries/mutations

* CoreAccountToken
* CoreAccountTokenCreate
* CoreAccountTokenDelete

Through a profile page it would be good to allow for users to create and manage their own tokens.

### Describe the Use Case

Allow users to create and delete API tokens.

**Comment by UXvsOpsMill** [comment]
https://github.com/opsmill/infrahub/assets/153716649/f4f0c997-6306-4d25-a2bf-93b0aac4639d

Figma Protoype : https://www.figma.com/proto/ZESJLTiQTzGJNFYw9fC5Nu/UX-Brain?page-id=2339%3A3253&node-id=2339-3254&viewport=1181%2C389%2C0.65&t=Yt49XmyQFOShX0a0-1&scaling=min-zoom&starting-point-node-id=2339%3A3254

**Comment by ogenstad** [comment]
I think it looks good! For now I think we can remove the "label" and only keep "name" Other than that from the list view we can remove the "API Keys" column as that will never contain any data. What I'd add is a pagination menu for the table with tokens but I'd expect that to look just as any other pagination we have throughout the app.

**Comment by BeArchiTek** [comment]
I think we will be able to replace https://github.com/opsmill/infrahub/issues/1388 with this issue
