### ISSUE TITLE
task: Replace class PrefixPool -> netaddr.IPSet

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#3547]
### Component

API Server / GraphQL

### Task Description

We should remove the custom [class PrefixPool](https://github.com/opsmill/infrahub/blob/infrahub-v0.14.0/backend/infrahub/pools/prefix.py#L9) with IPSet from the netaddr package. We already have this in place for IP Address pools.

**Comment by PhillSimonds** [comment]
I'll take this one.

**Comment by gmazoyer** [comment]
Fixed in https://github.com/opsmill/infrahub/commit/ae6981dea3a8e8fe1a40bbbb0f0f616428551f5a
