### ISSUE TITLE
bug: IPAddress and IPPrefix dropdown selectors in forms can't be filtered by IPNamespace

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3576]
### Component

Frontend UI

### Current Behavior

Some forms in the frontend, in which you can select an IP address, don't allow you to filter that list by IP Namespace.
This can be problematic, especially if you have IP addresses that exist in multiple namespaces.

### Expected Behavior

Whenever we need to select an IPAddress or IPPrefix in a form, we should allow the user to filter them by IP Namespace.

#### Assigning IP address to an interface
- `inv dev.start demo.load-infra-schema demo.load-infra-data`
- In the frontend goto the Interface list view
- Open the detailed view of an InfraIPAddressL3 node
- Goto the IP Addresses tab
- Click + icon
- In the form, there is no namespace selector

#### Create a device with primary IP address
- `inv dev.start demo.load-infra-schema demo.load-infra-data`
- In the frontend goto the device list view
- Click Add Device 
- In the form, there is no namespace selector for the primary IP address

**Comment by pa-lem** [comment]
could it be part of https://github.com/opsmill/infrahub/issues/2050 where we should be able to filter the parent, or is it a different and specific use case?

if the namespace is a parent of the prefix or the address, then we will be able to filter the parent first then selecting any object
