### ISSUE TITLE
bug: search anywhere does not show the namespace of nodes that inherit from the BuiltinIPAddress or BuiltinIPPrefix

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3577]
### Component

Frontend UI

### Current Behavior

When you search for an IP address or IP prefix using the search anywhere feature, it doesn't show the IP namespace in which they exist.
This makes it harder to identify the IP Address or IP Prefix you were searching for, especially if the node exists in more namespaces.
![image](https://github.com/opsmill/infrahub/assets/7521270/245491c7-38e4-48fc-9273-75d88152e1a7)

### Expected Behavior

The IP Namespace of nodes inheriting from BuiltinIPAddress or BuiltinIPPrefix, should be shown in the search anywhere results

### Steps to Reproduce

- `inv dev.start demo.load-infra-schema demo.load-infra-data`
- search for an IP Address or IP Prefix

**Comment by dgarros** [comment]
This is something we need to fix but I don't think this can be done just on the frontend today.

I think it's highlighting the need to refactor `display labels` to also include relationships, similar to what we can do with the `uniqueness_constraints` and the `hfid` now.
