### ISSUE TITLE
bug: Querying for a resource pool's resources will fail when it contains a resource that does not exist in the active branch

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3579]
### Component

API Server / GraphQL

### Current Behavior

You get an error message when you add a resource, that exists in a particular branch (not main), to a resource pool and then query for that resource pool together with its resources from another branch.

```json
{
  "data": {
    "CoreIPAddressPool": {
      "edges": [
        {
          "node": {
            "id": "17d5c235-71df-617a-3bb3-c515e9d364ac",
            "resources": null
          }
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Unable to find the node 17d5d677-f768-384b-3bb1-c51b26a1075f / BuiltinIPPrefix in the database.",
      "locations": [
        {
          "line": 6,
          "column": 9
        }
      ],
      "path": [
        "CoreIPAddressPool",
        "edges",
        0,
        "node",
        "resources"
      ]
    }
  ]
}
```

### Expected Behavior

I'm not sure if we should be able to do this, since a resource manager is branch agnostic. 
But if that is the case then we should prevent the user from doing so. 

### Steps to Reproduce

- `inv dev.start demo.load-infra-schema demo.load-infra-data`
- create a branch
- in the branch, create a new prefix
- add the prefix to an existing resource pool (for example the Management addresses pool)
- execute this graphql query from the main branch
```graphql
query {
  CoreIPAddressPool(name__value: "Management addresses pool") {
    edges {
      node {
        id
        resources {
         edges {
          node {
            display_label
          }
        }
        }
      }
    }
  }
}
```

**Comment by gmazoyer** [comment]
Fixed in https://github.com/opsmill/infrahub/commit/2f0af5ca7b60214c2f4cd829ec482e05196f157a
