### ISSUE TITLE
bug: cannot select a resource pool when adding an IP address to an InfraInterfaceL3 node

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3595]
### Component

Frontend UI

### Current Behavior

When you use the demo schema and data, and you want to assign an IP address to an interface then there is no ability to select a resource pool out of which you want to allocated an IP address.

The difference compared to other places is that the `ip_addresses` relationship from an InfraInterfaceL3 is defined with cardinality many. 

### Expected Behavior

Have the possibility to use a resource pool to allocate an IP address to the IntfraInterfaceL3

### Steps to Reproduce

- `inv dev.start demo.load-infra-schema demo.load-infra-data`
- in the web interface goto `Interfaces`
- Select any InfraInterfaceL3
- Navigate to the IP Addresses tab
- Click the + button
- There is no ability to select a resource pool

**Comment by dgarros** [comment]
This looks similar to https://github.com/opsmill/infrahub/issues/3469
@pa-lem please can you take a look

**Comment by pa-lem** [comment]
it's a different issue, there is no way yet to add a relationship using a pool

I'll take care of it
