### ISSUE TITLE
task: from_pool not available in the RelationshipAdd mutation

### ISSUE THREAD

**Issue by pa-lem** [opsmill/infrahub#3601]
### Component

API Server / GraphQL

### Task Description

Currently, it's not possible to add a new relationship with the `RelationshipAdd` mutation using a pool

For example, something like this won't work because `from_pool` is not available
```
mutation RelationshipAdd {
  RelationshipAdd(
    data: {
      id: "17d5c0c9-e93a-22b2-3b62-c51ea28df153",
      name: "ip_addresses",
      nodes: [
        {
          from_pool: {
            id: "17d5c0a7-577f-8e93-3b69-c51e621eb9ba"
          }
        }
      ]
    }
  ) {
    ok
    __typename
  }
}
```

```
Field 'from_pool' is not defined by type 'RelatedNodeInput'.
```

The only way to do it is to select a specific node and provide the id in the `nodes` array

This is a blocker for https://github.com/opsmill/infrahub/pull/3599

**Comment by gmazoyer** [comment]
> This is a bit more complicated than I thought initially
> 
> Currently we are have a specific RelatedNode object per type of pool which allow us to support specific properties per pool under `from_pool`
> 
> In order to support resource pool on the mutation `RelationshipAdd` we'll need to take a more generic approach that should work with all kind of pool. We need to take the common attribute between `PrefixPoolInput` and `IPAddressPoolInput`
> 
> @gmazoyer please can you take a look, please let me know if you have some questions

Comment from @dgarros from other issue

**Comment by gmazoyer** [comment]
Fixed in https://github.com/opsmill/infrahub/commit/91b91d3c4478467a6886bc63950ac16ad01ea5d6
