### ISSUE TITLE
task: Break apart infrahub/git/repository.py into smaller components

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#3625]
### Component

Git Integration

### Task Description

The file infrahub/git/repository.py is currently one of the largest files within the backend at 2300+ lines. The main features provided by this file are the classes `InfrahubRepository` and `InfrahubReadOnlyRepository`. Both of these classes provide an interface to Git both in terms of access through the local filesystem but also cloning, syncing, and merging remote repositories. Aside from this the classes have a number of other functions that operate with data within Git repositories but they aren't strictly related to Git as such. These are the classes that work with Jinja2 and Python transforms, Python Checks, Generators. I'd suggest that we lift these methods out of the main `InfrahubRepositoryBase` class and instead create a new class that takes a `InfrahubRepository` or `InfrahubReadOnlyRepository` as input and have this specialised class work with the SDK and anything defined within a .infrahub.yml file.

What remains in repository.py can also be split up into smaller files.

**Comment by dgarros** [comment]
@ogenstad are we good to close this one ?

**Comment by ogenstad** [comment]
Sure, we can pick it up again later. There are some other readability improvements that I'd like to do but the title would probably be different and the scope doesn't quite fit this issue regardless.
