### ISSUE TITLE
feature: computed attributes

### ISSUE THREAD

**Issue by ryanmerolle** [opsmill/infrahub#3637]
### Component

Not Sure

### Describe the Feature Request

Other DCIM solutions have the ability to create computed fields using Jinja or Python.  It would be nice to create this feature and tie it with read only attributes.

### Describe the Use Case

Tied with an attribute being read only like described in #3010 and #975, users could input a field like a physical address and the geohash or longitude/ latitude coordinates could be computed for use in the API for use by Grafana dashboards and other tooling.

**Comment by wvandeun** [comment]
Use case:
Dynamically generate the hostname of a device from other attributes/relationships defined on the device node

**Comment by ogenstad** [comment]
Fixed in a range of different PR's finally closed through #5302.
