### ISSUE TITLE
bug: artifact generation might run before the generators have finished as part of the CI in a proposed change

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3652]
### Component

API Server / GraphQL

### Current Behavior

When you open a proposed change, which triggers a generator to run as part of the CI, it could be that the generator might not yet have finished when the artifacts get regenerated.

This might lead to a situation where data changes made by the generators are not rendered in the artifacts. 

The user would need to manually trigger artifact generation after the the generator has finished, or make another change in the branch that would trigger the artifact generation tasks.

### Expected Behavior

We should have a method to define the order in which CI tasks run, so that we can control that artifact generation happens after the generators have completed. 

Or we should decouple the generator process from the CI pipeline.

### Steps to Reproduce

- load a demo instance from Infrahub development branch
- setup `infrahub-demo-edge-develop` as an external repository
- create a branch
- create a Backbone service object
- add the service object to the backbone_services group
- open a proposed change
- the generator will run and create new objects
- the changes done by the generator will not be shown in the generated artifacts

**Comment by ajtmccarty** [comment]
fixed in #3897
