### ISSUE TITLE
bug: Not able to add Profile into a Group (as members)

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#3681]
### Component

Frontend UI

### Current Behavior

When adding members into a group via the UI, it’s impossible to choose Profiles models 

### Expected Behavior

Be able to. Hose profiles objects as group members 

### Steps to Reproduce

With demo schema and data
- create a group
- Try adding a ProfileInfraInterfaceL3 as member into the group

**Comment by bilalabbad** [comment]
Hey! Thanks for the report. I tested this on the develop branch and confirmed that we can add a profile to a group.

However, the name is misleading. For example, with demo data, ProfileInfraInterfaceL3's name appears as InfraInterfaceL3. In the select options, we only display the name, not the kind.

Do you consider this a bug fix or a false positive?

**Comment by dgarros** [comment]
@bilalabbad this sounds like a bug, `ProfileInfraInterfaceL3` should appear in the list as well as `InfraInterfaceL3`. 
how is the frontend determining the list of possible options here ?

**Comment by bilalabbad** [comment]
`ProfileInfraInterfaceL3` does appear in the list. But its name is not explicit.

1. when you query `/api/schema/ProfileInfraInterfaceL3` on demo data, you get the follow response:
```
{
  "id": null,
  "state": "present",
  "name": "InfraInterfaceL3",
  "namespace": "Profile",
  "description": "Profile for InfraInterfaceL3",
  "label": "Infrainterfacel3",
  "kind": "ProfileInfraInterfaceL3",
  ....,
```

2. On the frontend, we use schema's `name` or `label` to display the select's options text.
<img width="434" alt="image" src="https://github.com/opsmill/infrahub/assets/15261980/d4d348da-434e-40bc-b6e7-71eff38c0420">

3. You can select any options and add it to the group. The only issue is that option's label are confusing

**Comment by BeArchiTek** [comment]
Shouldn’t we use the kind instead of just name and label ?
