### ISSUE TITLE
bug: CYPHER Relationship node property edges can be reversed during delete

### ISSUE THREAD

**Issue by ajtmccarty** [opsmill/infrahub#3690]
### Component

API Server / GraphQL

### Current Behavior

We expect the `IS_VISIBLE` and `IS_PROTECTED` edges in our cypher database to always go _from_ a `Node` or `Relationship` node _to_ a `Boolean` node, but this relationship can be reversed during a delete. For example
```
(:Relationship)<-[:IS_VISIBLE]-(:Boolean)
```

### Expected Behavior

In our database schema, we should never have an edge pointing _from_ a `Boolean` _to_ a `Node`. It might not be causing any issues right now, but it is illegal in our database

### Steps to Reproduce

Delete a relationship and then check it out on the database
from a unit test

    car_main = await NodeManager.get_one(db=db, branch=default_branch, id=car_accord_main.id)
    await car_main.owner.update(db=db, data={"id": person_jane_main.id})
    await car_main.save(db=db)

on the database

MATCH path = (:Boolean)-[]-(r:Relationship {name: "testcar__testperson"})-[:IS_RELATED]-(n:Node {uuid: "<car_main.id>"})

**Comment by ogenstad** [comment]
Were the failing tests incorrect before this?
