### ISSUE TITLE
Diff: logic to return a paginated diff

### ISSUE THREAD

**Issue by ajtmccarty** [opsmill/infrahub#3703]
### Component

API Server / GraphQL

### Describe the Feature Request

new logic to return a paginated diff

### Describe the Use Case

if a diff is too big, it takes a long time to load and is difficult to read. we should be able to paginate a diff in some predictable manner so that we can return a pieces of the diff in order

**Comment by dgarros** [comment]
this has been implemented and it will be part of 0.16
