### ISSUE TITLE
task: Refactor the demo script to load data

### ISSUE THREAD

**Issue by dgarros** [opsmill/infrahub#3733]
### Task Description

The goal is to refactor the script `models/infrastructure_edge.py` that is used to load the data into the demo environment to improve its performance. 
Some performance degradation are related to the new features introduced in the backend but there are some improvements that can be done by refactoring the code itself. _I can't find the PR but I remember we disabled the concurrency for part of the code at some point because it was triggering another issue_ 

Ideas to investigate
- Leverage the mutation RelationshipAdd to add members to group instead of updating the group itself [L321-L333](https://github.com/opsmill/infrahub/blob/develop/models/infrastructure_edge.py#L321-L333) & [L716-L721](https://github.com/opsmill/infrahub/blob/develop/models/infrastructure_edge.py#L716-L721)
- Leverage Batch as much as possible
- While working on the script it would be good to use the new features & best practices 
   - Use Prototype to improve typing
   - Use HFID to access the object in the store

**Comment by ogenstad** [comment]
Closing for this iteration with fixes from #3750, #3754, #3771 and #3773.
