### ISSUE TITLE
feature: Be able to use profile on generic

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#3737]
### Component

API Server / GraphQL

### Describe the Feature Request

As a user, I would like to create a Profile of a Generic type. This profile should then be applicable to all nodes derived from this generic type. (for the attributes ` inherited_from` the Generic)

### Describe the Use Case

Right now, when applying the same "changes" to two nodes derived from a common generic type, it is necessary to create two separate profiles. This requirement persists even if the nodes share a common generic type.

I would like to be able to create a Profile on the Generic and use this Profile on the derivated Nodes.

#### Example:
- **Generic Type**: InfraInterface
- **Derived Nodes**: InfraInterfaceL2 and InfraInterfaceL3

Right now, If I want to create a `disabled_interfaces` profile to enable/disable an interface, I must create two separate profiles—one for each node.

This behavior should be clearly documented and addressed to ensure users understand the necessity of maintaining separate profiles for each node, even when they are derived from a common generic type.

**Comment by ajtmccarty** [comment]
completed in #3742
