### ISSUE TITLE
feature: Separated the StandardGroup from the other in the `manager group` form/view

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#3738]
### Component

Frontend UI

### Describe the Feature Request

As a user, I would like to understand faster which groups are "managed" by me, versus the ones autogenerated by Infrahub due to Transformations or other internal Models.,

### Describe the Use Case

When clicking on the `manage group` button on a Node, we end up with `CoreGraphQLQueryGroup` and `CoreStandardGroup` mixed, which is confusing, and quite lengthy.

We may want to either split the groups per Model or remove the "auto-generated" group from this form/view

![image](https://github.com/opsmill/infrahub/assets/1334310/3906e8cd-b251-43f9-abe8-a1e1a2c9b431)

**Comment by bilalabbad** [comment]
We just merged it! I'll be happy to hear you feedback
