### ISSUE TITLE
feature: Add filters capabilities on IPAM views

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#3740]
### Component

Frontend UI, API Server / GraphQL

### Describe the Feature Request

As a user, I would like to be able to filter the prefixes I see in the tree and/or in the list based on filters.### 

### Describe the Use Case

If i have several hundreds or thousands of prefixes in the same namespace, the tree is getting quite long and I need to navigation is not handy, I would like to be able to filter some of the views and/or in the tree to find the node I want.

### Additional Information

When using`BuiltinIPPrefix` and `BuiltinIPAddress` Generics, we recommend hiding the node inheriting from it from the menu to avoid having several "IP Prefix" or "IP Address", but the filter's capabilities are only possible on the object views at the moment and not in the more complex IPAM ones.

Example from Netbox
<img width="515" alt="image" src="https://github.com/opsmill/infrahub/assets/1334310/613a0c4e-6792-47a9-bc6c-40d9dc0fc71d">
<img width="441" alt="image" src="https://github.com/opsmill/infrahub/assets/1334310/f9863966-f5cd-4668-b5c2-deb2f75ac6e9">

**Comment by bilalabbad** [comment]
The search results are going to be display as a flat list for this 1st iteration

**Comment by bilalabbad** [comment]
search input on IPAM tree is available
