### ISSUE TITLE
feature: Add total number of Prefixes into the tree view

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#3741]
### Component

Frontend UI

### Describe the Feature Request

As a user, I would to see the number of Prefixes present in the tree in the IPAM view

### Describe the Use Case

Similar to https://github.com/opsmill/infrahub/issues/3740, we want to promote the IPAM Views compare to the basic objects one for Ipam models. But number of results is not present.

**Comment by bilalabbad** [comment]
Hey ! Sure, you want the number of direct children or the number of descendants?
