### ISSUE TITLE
bug: Wrong icon in IPAM Prefix View

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#3743]
### Component

Frontend UI

### Infrahub version

0.15.0-dev

### Current Behavior

The icons and tooltip indicated this view are the exact opposite of the attribute

<img width="713" alt="image" src="https://github.com/opsmill/infrahub/assets/1334310/a0f9f2e3-2a83-451f-943d-e57fba626ce1">

https://www.loom.com/share/ffa7bb5dd3e14b9981d98859c03180d3?sid=4cdbdd2d-1518-4df8-8abe-6f1eb41b0f1b

### Expected Behavior

The icon and tolltip are aligned with the attribute configuration

### Steps to Reproduce

Using the demo schema and demo data
- create a couple of prefixes with the differents options
- check back on the parent prefixes views if the icon and tooltip are the good one

**Comment by bilalabbad** [comment]
Hey! Both icons have different meanings:
- the icon on the tree represents the type of the tree item
- tbe icon on the table represents the type of the member

So, the current behavior is "as expected."

However, I agree that it can be confusing at first glance. Perhaps displaying only an icon for the table's member type isn't the best solution. Ex: What if the member type doesn't have an icon?

Maybe we should display kind as text ? @dgarros @BeArchiTek @pa-lem

**Comment by bilalabbad** [comment]
merged.

on Ip prefix, member type is an attribute of type Dropdown. This PR displays the value as Dropdown instead of just an icon
