### ISSUE TITLE
feature: Protect `main` branch from changes

### ISSUE THREAD

**Issue by petercrocker** [opsmill/infrahub#3765]
### Component

Not Sure

### Describe the Feature Request

Add an option to protect the `main` branch in Infrahub, similar to how GitHub/GitLab can enforce this behavior in a git repo.

Needs to be an option, as during testing/labs this could be annoying to enforce. Needs to be decided if the default is ON or OFF. Value of defaulting to ON would be nudging users to use branches during testing, and a production-ready setting. Defaulting to OFF could potentially make testing simpler.

### Describe the Use Case

This protection concept is used by IaC practitioners today in their git-based workflows.

**Comment by ogenstad** [comment]
If we don't start to change the internals it could be that this should be a permission, perhaps one that the admin role doesn't have by default (though the admin user would have it by default). The reasoning is when we are syncing git repositories and there are updates on the `main` branch we might still want the git-agent user to make changes in the default branch.
