### ISSUE TITLE
bug: branch detail page doesn't open when the branch name contains a /

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3874]
### Component

Frontend UI

### Infrahub version

0.15.0

### Current Behavior

When you create a branch which contains a / in the name, you cannot open its branch detail page.

### Expected Behavior

The branch detail page opens, or we prevent people to create a branch with a / in the name.

### Steps to Reproduce

In the UI, create a branch with a / in the name.
Navigate to the branch list view and click on the branch.

**Comment by bilalabbad** [comment]
fixed
