### ISSUE TITLE
bug: no proper error message when certificate validation for external repository fails

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3875]
### Component

Git Integration

### Infrahub version

0.15.0

### Current Behavior

When you set up an external repository on a git server, that uses a self signed certificate or a certificate that is signed by a non-trusted CA it fails to sync that repository. The error message that you see in the task logs is not clear.

![image](https://github.com/user-attachments/assets/d662487e-3a55-42a1-96e1-3dd689901f4a)

### Expected Behavior

There should be a clear error message stating what exactly went wrong when trying to connect to the external git repository.

### Steps to Reproduce

Information was provided to me as-is. I have not tried to reproduce it yet.

**Comment by dgarros** [comment]
Good timing, Improving errors reporting around Git repository is one of the main goal if the next release,
