### ISSUE TITLE
feature: Add link to related node in the list view

### ISSUE THREAD

**Issue by dgarros** [opsmill/infrahub#3889]
### Component

Frontend UI

### Describe the Feature Request

When displaying the table with all objects of a same kind (list view), it's currently not possible to directly display the detailed page of a related node. The user must display the detailed page of a node then click on the related node to display its information.

Ideally all related nodes should be directly accessible from the list view.

in the screenshot below, `Site`, `Platform`, `IP Address` and `ASN` are related objects but it's not possible to navigate to these objects directly from this page.
![Screenshot 2024-07-22 at 13 24 59](https://github.com/user-attachments/assets/f0d29cb4-c07e-4181-ad11-1030901018ff)

![Screenshot 2024-07-22 at 13 28 25](https://github.com/user-attachments/assets/0238a522-515d-486f-b604-07ee5093c44b)

### Describe the Use Case

Simplify the navigation in the frontend and reduce the number of click to navigate to the right information

**Comment by bilalabbad** [comment]
merged 🥳
