### ISSUE TITLE
bug: adding member to group uses wrong branch

### ISSUE THREAD

**Issue by ajtmccarty** [opsmill/infrahub#3898]
### Component

Frontend UI

### Infrahub version

0.15.1

### Current Behavior

trying to add a member to a group while on a branch where the new member only exists on the branch (and does not exist on `main`) fails with an object not found toast error

### Expected Behavior

the new member should be saved to the group on the branch successfully

### Steps to Reproduce

1. make a group on `main`
2. make a branch
3. make a new object of any type that can be added to a group on your branch
4. try to add the new object to a group while on your branch

### Additional Information

it looks like the front-end is trying to send a RelationshipAdd mutation to `main` regardless of the currently selected branch
the RelationshipAdd mutation will succeed if done manually via the GraphQL explorer on the correct branch

**Comment by wvandeun** [comment]
Just wanted to add, that we have different demo using generators where we rely on this feature to work.
