### ISSUE TITLE
bug: HFID is not properly set for RelatedNode in the Python SDK

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3899]
### Component

Python SDK

### Infrahub version

0.12.0

### Current Behavior

When you query a node and its relationships using the Python SDK, the HFID of the related nodes does not seem to be correctly set for relationships that are retrieved by default.

### Expected Behavior

The HFID of the related nodes should be properly set, if there is an HFID defined in the schema.

### Steps to Reproduce

- load demo schema
- run the following code
```python
from infrahub_sdk import InfrahubClientSync, Config

client = InfrahubClientSync.init(config=Config())
site = client.create("LocationSite", name="site1")
site.save()
print(site.hfid) # site hfid is properly set

device = client.create("InfraDevice", name="device1", site="site1", type="ASR1002-HX")
device.save()

device = client.get("InfraDevice", name__value="device1")
assert device.site.initialized
assert device.site.hfid is not None # hfid is not set

device.site.fetch()
assert device.site.hfid is not None # hfid is set
```
- Notice that the hfid of the RelatedNodeSync is not set

**Comment by gmazoyer** [comment]
Fixed in https://github.com/opsmill/infrahub/commit/b2da9b8aea0e4484aa887d7871f5a51a6064cf9b
