### ISSUE TITLE
bug: HFID of a node is not properly set when using prefetch_relationships in the Python SDK

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3900]
### Component

Python SDK

### Infrahub version

0.12.0

### Current Behavior

When you use the `prefetch_relationships` to retrieve the relationships of a node in the Python SDK, the HFID of all the related nodes does not seem to be properly set.

### Expected Behavior

The HFID of all the retrieved related nodes should be properly set

### Steps to Reproduce

- load demo 
- run the following code
```python
from infrahub_sdk import InfrahubClientSync, Config

client = InfrahubClientSync.init(config=Config())
site = client.create("LocationSite", name="site1")
site.save()
print(site.hfid) # site hfid is properly set

device = client.create("InfraDevice", name="device1", site="site1", type="ASR1002-HX")
device.save()

device = client.get("InfraDevice", name__value="device1", populate_store=True, prefetch_relationships=True)
print(device.site.peer.hfid) # prints ['None']
print(device.site.peer.id)

print(client.store.get(key=site.id).hfid) # prints ['None']
```

**Comment by wvandeun** [comment]
It seems that also other attributes of the relationships do not get properly set:
```python
device = client.get("InfraDevice", name__value="device1", populate_store=True, prefetch_relationships=True)
print(device.site.peer.name.value) # None
print(device.primary_address.peer.address.value) # None
```

**Comment by wvandeun** [comment]
related to opsmill/infrahub-sdk-python#15 ?

**Comment by gmazoyer** [comment]
Fixed in https://github.com/opsmill/infrahub/commit/56abac7dd18ee9926a408321416239c4e79a1121
