### ISSUE TITLE
feature: ability to use HFID as a filter for GraphQL queries

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3908]
### Component

API Server / GraphQL

### Describe the Feature Request

We need to add a capability to retrieve a node using it's HFID using the GraphQL API.
This feature will then need to be exposed through the Python SDK as well.

### Describe the Use Case

As a user I want to be able to retrieve a node via GraphQL using it's HFID.

**Comment by gmazoyer** [comment]
Fixed in https://github.com/opsmill/infrahub/commit/766d2660331892bb202d916e3f76d25878dc3afd
