### ISSUE TITLE
bug: unable to use an HFID made up of multiple attributes/relationships for mutations in the SDK

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3909]
### Component

Python SDK

### Infrahub version

0.12.0

### Current Behavior

You are unable to create a node using the SDK, and simulteanously adding a relations to another node using it's HFID, if the HFID is made up of multiple attribute values (or relationship attribute values).

### Expected Behavior

We are able to create a relationship to a node using it's HFID, if the HFID is made up of multiple attribute values.

### Steps to Reproduce

- load the demo schema
- load the demo data
- execute the following script, we will try to create a new InfraDevice and set the relation to InfraAutonomousSystem AS64496. InfraAutonomousSystem has a HFID made up of `name__value` and `asn__value`.
```python
from infrahub_sdk import InfrahubClientSync, Config
client  = InfrahubClientSync.init(config=Config())
device = client.create("InfraDevice", name="test", site="atl1", type="dummy", asn=["AS64496", "64496"])
device.save() #  raises GraphQLError exception
 
device = client.create("InfraDevice", name="test", site="atl1", type="dummy", asn="AS64496 64496")
device.save() # raises GraphQLError exception
```

**Comment by gmazoyer** [comment]
Fixed in https://github.com/opsmill/infrahub/commit/b21b674b1879b964d76d9b4942b276f7177388f4
