### ISSUE TITLE
task: Documentation around uniqueness_constraints is indicating some wrong informations

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#3924]
### Component

Documentation & Examples

### Task Description

https://docs.infrahub.app/topics/schema/#uniqueness-constraints
![image](https://github.com/user-attachments/assets/8860c29f-7fd8-49c5-b02d-0c188c3f3b69)

Uniqueness Constraints is a list[list[str]] so the documentation is not ok

**Comment by gmazoyer** [comment]
Fixed in https://github.com/opsmill/infrahub/commit/8917038e40d2ac05820a399bf66fe49be35c19bf
