### ISSUE TITLE
bug: buttons partially cover the query in GraphQL query detail page

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3927]
### Component

Frontend UI

### Infrahub version

0.16.0.dev0

### Current Behavior

On a smaller screens (resolution 1512x982 - macbook laptop screen), the GraphQL query on the GraphQL query detail page is covered by buttons. You can't read the whole contents of the query, without copying it somewhere else.
This doesn't seem to be an issue on larger screens.

<img width="1233" alt="image" src="https://github.com/user-attachments/assets/8bdb216e-8a94-4763-bca5-6830393a8bc4">
 

### Expected Behavior

The GraphQL query is completely visible.

### Steps to Reproduce

- load demo schema / data
- add demo-edge repository to Infrahub
- navigate to the GraphQL query list view
- open check_backbone_link_redundancy

**Comment by bilalabbad** [comment]
merged on stable
