### ISSUE TITLE
bug: tree view in all groups view is misleading

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3928]
### Component

Frontend UI

### Infrahub version

0.16.0.dev0

### Current Behavior

CoreStandardGroups are displayed differently then other groups (for example GraphQLQuery Groups). CoreStandardGroups are indented more and have a small circle in front of them.

Because the groups are sorted alphabetically this creates the impression that some groups are a child of the less indented group, which is very confusing.

<img width="1248" alt="image" src="https://github.com/user-attachments/assets/a5783ef0-b944-4d8d-90ff-7db0d4e8666d">

### Expected Behavior

All groups at the same level in a hierarchy should have the same indentation level and should the same circle in front of them

### Steps to Reproduce

- load demo schema
- load demo data
- add demo-edge as read-only repository
- wait till after artifact generation has occurred
- go to to the all groups page

**Comment by bilalabbad** [comment]
should be fixed on stable :)
