### ISSUE TITLE
bug: Comment input content not cleared

### ISSUE THREAD

**Issue by BaptisteGi** [opsmill/infrahub#3942]
### Component

Frontend UI

### Infrahub version

0.15.1

### Current Behavior

When I post a comment in "Proposed Change" page the input isn't cleared after I pressed "Comment"

<img width="1562" alt="image" src="https://github.com/user-attachments/assets/1a94e6a8-fc3c-4905-b63b-aaf5cfec1ddc">

### Expected Behavior

I expect the input to be empty after having submitted my comment

### Steps to Reproduce

- Create a proposed change
- Post a comment
- "Add a comment" box still contains my previous comment content

**Comment by bilalabbad** [comment]
done
