### ISSUE TITLE
feature: add clickable items in the proposed change list view

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3990]
### Component

Frontend UI

### Describe the Feature Request

The new proposed change list view adds new icons and data columns. It would be useful to make these items clickable.
IE when you click on the (+) icon it opens the proposed change on the data tab.
When you clack on the number in the tasks column it takes you to the tasks tab of the proposed change.

### Describe the Use Case

Make navigation in the front-end intuitive and quick.

**Comment by bilalabbad** [comment]
merged
