### ISSUE TITLE
bug: On object update mutation, we cannot use a number pool on a number attribute

### ISSUE THREAD

**Issue by bilalabbad** [opsmill/infrahub#4042]
### Component

API Server / GraphQL

### Infrahub version

0.16.0

### Current Behavior

On mutation [Kind]Update, number attribute do not have `from_pool`. Thus, we cannot associate a number pool when editing  an object (only when we create a new object)

### Expected Behavior

Being able to use a number pool when editing an object. Number attribute should allow `from_pool` like on [Kind]Create mutation

### Steps to Reproduce

- Check graphql schema of a number attribute with a number pool

**Comment by gmazoyer** [comment]
This should be fixed in both develop and release-0.16 branch since [this commit](https://github.com/opsmill/infrahub/commit/92983a9f3d512277336343e30869037d3ff0a811).
