### ISSUE TITLE
feature: Attribute property to distinguish user input from schema's default value

### ISSUE THREAD

**Issue by bilalabbad** [opsmill/infrahub#4057]
### Component

API Server / GraphQL

### Describe the Feature Request

We need a property that indicates whether the current value of an attribute is based on user input or if it’s using the schema's default value.

### Describe the Use Case

Example of use case:

In an edit form, the value provided by the user should override the value from a predefined pool. The value from the pool, in turn, has a higher priority than the default value specified by the schema.

However, if the value of a field matches the default value defined in the schema, there's no way to tell whether the user deliberately set the field to that value or if it's simply using the default.

**Comment by dgarros** [comment]
Every attribute in GraphQL has a property `is_default` that is meant to indicate pretty much what you are describing.

```graphql
query {
  InfraPlatform(ids: ["17eae6db-c75c-6085-1209-c5106d3d4db1"]) {
    edges {
      node {
        id
        name {
          value
          is_default
        }
        description {
          value
          is_default
        }
      }
    }
  }
}
```

```json
{
  "data": {
    "InfraPlatform": {
      "edges": [
        {
          "node": {
            "id": "17eae6db-c75c-6085-1209-c5106d3d4db1",
            "name": {
              "value": "Arista EOS",
              "is_default": false
            },
            "description": {
              "value": null,
              "is_default": true
            }
          }
        }
      ]
    }
  }
}
```

**Comment by bilalabbad** [comment]
thanks. I'll open a PR to handle it

**Comment by bilalabbad** [comment]
Frontend now handle is_default. I'll close this issue.
