### ISSUE TITLE
bug: Generator can't run on nodes that don't have "name" attribute

### ISSUE THREAD

**Issue by BaptisteGi** [opsmill/infrahub#4062]
### Component

API Server / GraphQL

### Infrahub version

0.15.2

### Current Behavior

When I run my generator in the "proposed changes" view it fails with a message: `"'InfraCircuitInfrahubNode' object has no attribute 'name'"`.

### Expected Behavior

I was expecting my generator to go through and generate endpoint related data ...

### Steps to Reproduce

- Spin demo instance with demo data-set (invoke demo.build demo.start demo.load-infra-schema demo.load-infra-data)
- Connect demo edge git repo to it (https://docs.infrahub.app/tutorials/getting-started/git-integration)
- Create a branch
- On that branch create a **Circuit** object
- Add this circuit to the `provisioning_circuits` group
- Create a proposed change toward main branch
- In the **Checks** section the `create_circuit_endpoints` Generator is failing with the error message

### Additional Information

- Looking at the logs this line is mentioned https://github.com/opsmill/infrahub/blob/develop/backend/infrahub/message_bus/operations/requests/generator_definition.py#L104
- Extending the Circuit object with an attribute 'name' did solve the issue ...
- Maybe artifacts have the same behaviour...

**Comment by ogenstad** [comment]
It's the same for artifact_definitions. We should use "display_label" instead of the name attribute.
