### ISSUE TITLE
feature: Ensure Swagger/Redoc docs is accessible offline

### ISSUE THREAD

**Issue by bilalabbad** [opsmill/infrahub#4063]
### Component

API Server / GraphQL

### Describe the Feature Request

Make Swagger accessible from an environment that is blocking every external request / is offline:

### Describe the Use Case

Swagger docs accessible at `/api/docs` download source code from CDN. Thus if you have a restricted environment or are working offline, you cannot access it.

```
https://fastapi.tiangolo.com/img/favicon.png
https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js
https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css
```

### Additional Information
Related doc: https://fastapi.tiangolo.com/how-to/custom-docs-ui-assets/#self-hosting-javascript-and-css-for-docs

**Comment by ogenstad** [comment]
Fixed in #4065.
