### ISSUE TITLE
bug: GraphQL query isn't showing up in the details page

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#4105]
### Component

Frontend UI

### Infrahub version

0.16.0.dev

### Current Behavior

When looking at a GraphQL query the actual query doesn't show up.

![Screenshot 2024-08-14 at 14 19 20](https://github.com/user-attachments/assets/19d1d58a-486e-4fd8-ad9b-546f63f6b970)

### Expected Behavior

The stored query should be visible on the form

### Steps to Reproduce

1. Start an instance of infrahub
2. Load or create a GraphQL query
3. Visit the query object

**Comment by bilalabbad** [comment]
thanks. fixed
