### ISSUE TITLE
bug: Can't close a thread opened on an Artifact

### ISSUE THREAD

**Issue by BaptisteGi** [opsmill/infrahub#4189]
### Component

API Server / GraphQL

### Infrahub version

0.16.0

### Current Behavior

When I click on "resolve thread" for a comment opened on an Artifact I have an error message
![image](https://github.com/user-attachments/assets/7cc4a7a5-eb6a-4915-8079-1242229e693f)

### Expected Behavior

I expect my thread to be resolved ...

### Steps to Reproduce

- Spin demo instance with demo data-set (invoke demo.build demo.start demo.load-infra-schema demo.load-infra-data)
- Connect demo edge git repo to it (https://docs.infrahub.app/tutorials/getting-started/git-integration)
- Create a Proposed change with one of the existing branch
- Comment one artifact (If no artifact try to regenerate / change branch)
- From the main Proposed Change view, try to resolve the thread

**Comment by bilalabbad** [comment]
Should be fixed on develop :)
