### ISSUE TITLE
feature: Support for Multi-Select dropdown in Schema

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#4220]
### Component

Frontend UI, API Server / GraphQL

### Describe the Feature Request

Currently, the schema supports those two types of selection fields:
- **Dropdown**: A single-select dropdown that allows the user to choose one item from a list.
- **List**: A field that supports multiple items, but without a predefined set of choices.

As a user, I would like to be able to select multiple items from a predefined list of choices.

To do that right now, I can use another node and consume it with a cardinality `many`, but contrary to `Dropdown` I can't have color, which would make-it more visual.

### Describe the Use Case

I have a list of choices that should not grow, so having a specific node for it is "overkill"

Example:
- Juniper encapsulation options

**Comment by ogenstad** [comment]
Potentially a duplicate of #1770?

**Comment by BeArchiTek** [comment]
Indeed duplicate
