### ISSUE TITLE
feature: Support deprecated field in the schema

### ISSUE THREAD

**Issue by dgarros** [opsmill/infrahub#4245]
### Component

API Server / GraphQL

### Describe the Feature Request

As an Infrahub Developer I want to be able to change the structure of the schema and I want to be able to indicate to the users which field has been deprecated and will be removed in a future version

### Describe the Use Case

Provide best in class schema

**Comment by gmazoyer** [comment]
Schema/backend implementation has been done in https://github.com/opsmill/infrahub/commit/0e3b758c23108774aca24558b1c1ee42426c4847. We probably need to have something in the frontend to show that a field is deprecated to users.
