### ISSUE TITLE
bug: Inconsistent Proposed Changes Page Layout

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#4314]
### Component

Frontend UI

### Infrahub version

0.16

### Current Behavior

 The layout of the "Proposed Changes" page is inconsistent with the other pages. The `+` button is small and placed at the top-right corner, which impacts the user experience.

### Expected Behavior

The layout should be consistent across all pages, with the + button having the same size and position.

### Steps to Reproduce

- using the demo schema and demo data
- create a branch and open a Proposed Change

**Comment by bilalabbad** [comment]
It currently tag for 0.16, but I do not see this in the latest release. Can you give me the URL to see this view?

**Comment by bilalabbad** [comment]
not reproductible
