### ISSUE TITLE
bug: "Retry All" Button for Checks is Too Small

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#4315]
### Component

Frontend UI

### Infrahub version

0.16

### Current Behavior

The "Retry All" button for checks is too small, making it difficult for users to interact with.

### Expected Behavior

The "Retry All" button should have a larger, more visible size for ease of use.

### Steps to Reproduce

Trigger a failed check.
Observe the size and placement of the "Retry All" button.

**Comment by bilalabbad** [comment]
merged. Screenshots are visible in the related PR.
