### ISSUE TITLE
bug: Form Closes When Clicking Outside Without Validation

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#4317]
### Component

Frontend UI

### Infrahub version

0.16

### Current Behavior

Clicking outside of a form closes it, which is frustrating if data has already been entered. There should be a cache or validation to prevent data loss.

### Expected Behavior

The form should either save the data or prompt validation before closing to prevent accidental data loss.

### Steps to Reproduce

Start filling out a form.
"Accidentally" click outside the form.

**Comment by bilalabbad** [comment]
good one. I agree 👍🏼
