### ISSUE TITLE
bug: create/update mutation allows you to set a parent for the "root" of a hierarchy

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4325]
### Component

API Server / GraphQL

### Infrahub version

0.16.0.dev0

### Current Behavior

When you define a hierarchy in the schema, we define the root of hierarchy by specifying setting an empty parent.
We should therefor not be able to set a parent for nodes that are at the root level of the hierarchy. 
It seems that it is possible to set a parent for nodes at the root level, as long as the node that you want to add a parent is inheriting from the generic that defines the hierarchy.

### Expected Behavior

We should not be able to define a parent for a node that is at the root of a hierarchy.

### Steps to Reproduce

- load instance of Infrahub
- load the demo schema
- load the demo data
- navigate to continent in the web UI
- select Europe and click on the edit button
- in the parent dropdown select country
- set the country to Australia
- click save
- Austrailia is now the parent of Europe
- Europe dissapears from the hierarchy tree under Australia

**Comment by dgarros** [comment]
Fixed in https://github.com/opsmill/infrahub/pull/4414
