### ISSUE TITLE
bug: Repository initialization silently failing

### ISSUE THREAD

**Issue by BaptisteGi** [opsmill/infrahub#4334]
### Component

Git Integration

### Infrahub version

0.16.0

### Current Behavior

If I add a repository with a faulty `.infrahub.yml` definition it fails however it looks perfectly fine from UI overview.

<img width="790" alt="image" src="https://github.com/user-attachments/assets/2220debd-3572-400f-8713-d572acac80ba">

<img width="812" alt="image" src="https://github.com/user-attachments/assets/22efbc9d-8144-4825-b4b5-676174dbcf3b">

<img width="812" alt="image" src="https://github.com/user-attachments/assets/9b8c6ef8-0cb1-47f0-a421-f16c9afe519a">

**This means all features coming from that repo (checks, generators ...) are not imported...**

### Expected Behavior

If the init fails for some reason I expect the status to switch to error

### Steps to Reproduce

- invoke dev.build dev.start
- Add repository https://github.com/BaptisteGi/basic-repo without the `queries` section
- Check the repository page

### Additional Information

I don't know if it's only related to the `queries` section or if it's a wider issue

**Comment by ogenstad** [comment]
Fixed in #4436.
