### ISSUE TITLE
bug: unreadable error message when you provide incorrect credentials for an external repository in the frontend 

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4343]
### Component

Frontend UI, API Server / GraphQL

### Infrahub version

0.16.0

### Current Behavior

When you try to add a repository to Infrahub using wrong credentials, Infrahub correctly shows you an error message. But the error message is not readable for an end-user. Some of the critical information in the error message seems to wrapped out of the pop-up message. Due to this a user is unable to understand what is wrong. 
![image](https://github.com/user-attachments/assets/5addf736-6124-4dad-8233-bc92c46532ab)

### Expected Behavior

Infrahub should show a clear error message

### Steps to Reproduce

- spin up an instance of Infrahub
- add a new repository, use wrong credentials

**Comment by ogenstad** [comment]
Can you describe how you are starting Infrahub?

When I test from `stable` with `inv demo.start` I get this:

![Screenshot 2024-09-12 at 13 22 05](https://github.com/user-attachments/assets/3f345381-fa2e-40c2-8b2a-abac38a3a306)

**Comment by wvandeun** [comment]
This seems to have been fixed in https://github.com/opsmill/infrahub/pull/3812
