### ISSUE TITLE
bug: The repository form doesn't have a "cancel" button

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#4402]
### Component

Frontend UI

### Infrahub version

0.16.0

### Current Behavior

The form to add a repository is different compared to the dynamic forms, probably due to this it doesn't have a cancel button so it's a bit inconsistent.

![Screenshot 2024-09-20 at 14 02 04](https://github.com/user-attachments/assets/56f427a7-7747-476c-8418-569b81e10c5b)

### Expected Behavior

The form should have a cancel button

### Steps to Reproduce

Start Infrahub and go to the form to create a repository.

**Comment by bilalabbad** [comment]
merged in stable
