### ISSUE TITLE
bug: hfid is `null` for related nodes when querying a node and its related nodes using GraphQL

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4482]
### Component

API Server / GraphQL

### Infrahub version

0.16.1

### Current Behavior

When you use a GraphQL query  to get a node and its related nodes, then the `hfid` of the related nodes is `null`.

### Expected Behavior

The HFID of the related nodes will be populated.

### Steps to Reproduce

- load infrahub with demo schema and data
- execute the following GraphQL query
```graphql
query {
  LocationSite(name__value: "atl1") {
    edges {
      node {
        id
        hfid 
        devices {
          edges {
            node {
              hfid
            }
          }
        }
      }
      
    }
  }
}
```
In the result you will see that all the devices have an HFID value `null`

**Comment by ogenstad** [comment]
With the below query it is working as expected which indicates that the problem is that we just populate the hfid with data that we already have available and that we don't consider this as required data to fetch in order to populate an HFID. The resolvers will have to take this into consideration.

```graphql
query {
  LocationSite(name__value: "atl1") {
    edges {
      node {
        id
        hfid 
        devices {
          edges {
            node {
              hfid
              name { value }
            }
          }
        }
      }
    }
  }
}
```
