### ISSUE TITLE
bug: de-allocted resources are not properly removed from a CoreNumberPool

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4617]
### Component

API Server / GraphQL

### Infrahub version

0.16.3

### Current Behavior

When you allocate a number from a number pool, to an attribute of a node and then remove the node, then the number stays allocated within the resource pool.

### Expected Behavior

The number should be returned back to the pool as an available resource.

### Steps to Reproduce

- load infrahub with demo data and schema
- create a number pool, node type InfraInterfaceL2, attribute speed
- create a new L2 Interface, for the speed attribute use the number pool
- delete the L2 interface
- open the number resource pool detail page and click on the view button
- the allocated number will show up twice in the list, referencing the id of the node that we deleted
![image](https://github.com/user-attachments/assets/979cc3b0-e96e-46e0-ae04-25cbe65d8994)

**Comment by ogenstad** [comment]
Fixed in #4676.
