### ISSUE TITLE
feature: filter hierarchical nodes by the parents in node create/edit form in the frontend

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4636]
# 
## 
### Component

Frontend UI

# 
## 
### Describe the Feature Request

In [https://github.com/opsmill/infrahub/pull/3679|https://github.com/opsmill/infrahub/pull/3679] we implemented a feature that would allow you to filter related nodes by their parent, if they have a relationship of kind Parent. 

We would like to have the same functionality for nodes that are part of a hierarchy.

# 
## 
### Describe the Use Case

Given the demo schema, when I want to create a new device using the frontend, I have to select the site that it belongs to.

When I have 1000 sites in Infrahub, this becomes a very long list that I need to select the right site from.

Since a site is part of a hierarchy, it would be useful if I could filter the list of sites by it's ancestors in the hierarchy (Country > Continent).

This is similar to how we do this for relationships that have a parent relationship to another node, for example an interface.

# 
##

**Comment by bilalabbad** [comment]
Feature will be available in 1.1
