### ISSUE TITLE
task: Improve proposed change shortcut from branch menu

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#4678]
### Component

Frontend UI

### Task Description

From the branch menu when click to create a proposed change it would be nice if the branch from the current page was selected as the source branch automatically.

![Screenshot 2024-10-22 at 09 41 51](https://github.com/user-attachments/assets/aa0d9827-bd38-4aeb-b51c-1e592bc3852d)

**Comment by dgarros** [comment]
this is a good point
also I think we should use the dedicated form to create a proposed change
![Screenshot 2024-10-22 at 11 11 46](https://github.com/user-attachments/assets/df87224a-9039-4717-a132-81f9bbc6ddb1)
