### ISSUE TITLE
bug: when using pagination in a graphql query, the same node seems to be returned on different pages

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4700]
### Component

API Server / GraphQL

### Infrahub version

0.16.4, develop

### Current Behavior

When you use pagination on a GraphQL query (offset and limit filters), the same node seems to be returned on different pages.

### Expected Behavior

The same node should never be returned on different pages, unless there is an overlap.

### Steps to Reproduce

- load an instance of Infrahub with the demo schema and data
- open the GraphiQL interface
- execute the following GraphQL query
```graphql
query {
 Infranterface(limit: 2) {
  edges {
    node {
      id
    }
  }
 }
}
```
- take note of the node ids that got returned
- query the next page, by introducing an offset filter with value 2 and check the ids, one of the nodes returned will also be in the first query
```graphql
query {
 InfraInterface(offset: 2, limit: 2) {
  edges {
    node {
      id
    }
  }
 }
}
```
- query the next page, by introducing an offset filter with value 4
```graphql
query {
 InfraInterface(offset: 4, limit: 2) {
  edges {
    node {
      id
    }
  }
 }
}
```
- query the next page, by introducing an offset filter with value 6, one of the nodes returned will also be in the first query
```graphql
query {
 InfraInterface(offset: 6, limit: 2) {
  edges {
    node {
      id
    }
  }
 }
}
```

**Comment by ogenstad** [comment]
Fixed in #4704.
