### ISSUE TITLE
bug: The button to close a proposed change is disabled

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#4800]
# 
## 
### Component

Frontend UI

# 
## 
### Infrahub version

1.0.0

# 
## 
### Current Behavior

After I open a proposed change I'm not able to close it again.

![Screenshot 2024-10-31 at 10 06 58]([https://github.com/user-attachments/assets/ad98b89c-2f98-491c-a885-caf81c34f7d2|https://github.com/user-attachments/assets/ad98b89c-2f98-491c-a885-caf81c34f7d2])

We can see in the code that the button is disabled

# 
## 
### Expected Behavior

I should be able to close a proposed change

# 
## 
### Steps to Reproduce

1. Open a new proposed change

2. Try to close it.

# 
##

**Comment by FragmentedPacket** [comment]
Resolved in #5105
