### ISSUE TITLE
bug: Invalid error message when trying to load files not found in a repo through the /api/file endpoint

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#4829]
### Component

API Server / GraphQL

### Infrahub version

1.0.0

### Current Behavior

If you try to access a file that's not found within a repo we currently get an invalid response instead of the correct error message.

The relevant code in the API:
https://github.com/opsmill/infrahub/blob/infrahub-v1.0.0/backend/infrahub/api/file.py#L62-L63

```python
    response = await service.message_bus.rpc(message=message, response_class=GitFileGetResponse)
    return PlainTextResponse(content=response.data.content)
```

When we hit the error condition:
https://github.com/opsmill/infrahub/blob/infrahub-v1.0.0/backend/infrahub/message_bus/operations/__init__.py#L83-L84

```python
    except Exception as exc:  # pylint: disable=broad-except
        if message.reply_requested:
            response = RPCErrorResponse(errors=[str(exc)], initial_message=message.model_dump())
            await service.reply(message=response, initiator=message)
```

When parsing the response:

https://github.com/opsmill/infrahub/blob/infrahub-v1.0.0/backend/infrahub/services/adapters/message_bus/rabbitmq.py#L226-L227

```python
    async def rpc(self, message: InfrahubMessage, response_class: type[ResponseClass]) -> ResponseClass:
        correlation_id = str(UUIDT())

        future = self.loop.create_future()
        self.futures[correlation_id] = future

        log_data = get_log_data()
        request_id = log_data.get("request_id", "")
        message.meta = Meta(request_id=request_id, correlation_id=correlation_id, reply_to=self.callback_queue.name)

        await self.service.send(message=message)

        response: AbstractIncomingMessage = await future
        data = ujson.loads(response.body)
        return response_class(**data)
```

The problem here is that when there is an error the data that comes back is a json payload where `**data` can be loaded into a `RPCErrorResponse` but we are trying to load it into a `response_class` object which in this case is a `GitFileGetResponse` so the this fails.

### Expected Behavior

If I try to get a file that doesn't exist the error message should indicate as much

### Steps to Reproduce

1. Create a repo and note the id
2. Try to get a file that doesn't exist:

```bash
❯ curl http://localhost:8000/api/file/1803d794-f2b1-1a78-58da-1746e8ef299d/i-do-not-exist.txt
{"data":null,"errors":[{"message":"Field required","extensions":{"code":400}}]}%
```

### Additional Information

It's probably been like this for quite some time but it should be fixed and we need to add tests to validate that it's working as expected. Alternatively as this part gets converted to Prefect we could ensure to fix it then.

**Comment by lykinsbd** [comment]
@LucasG0 I am trying to tie this to a specific PR and update the milestone. Do you know where this was fixed?

**Comment by ogenstad** [comment]
@lykinsbd, should be this one: https://github.com/opsmill/infrahub/pull/5139
