### ISSUE TITLE
bug: Inconsistency in resources manager creation form

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#4850]
### Component

Frontend UI

### Infrahub version

1.0.1

### Current Behavior

When creating a "normal" object, the button is `save`
When creating a resource pool, the button is `save` for Prefix Pool and for IP Pool but is `create` for a Number Pool

![image](https://github.com/user-attachments/assets/b5ba4cae-c30a-4665-8789-1cf4263afd41)
![image](https://github.com/user-attachments/assets/47799062-6816-45e3-96d8-38aed773c9ef)
![image](https://github.com/user-attachments/assets/a00ee909-1e39-49c6-8163-c66ee3b66f3f)

### Expected Behavior

Unified button across forms

### Steps to Reproduce

Load infrahub with demo.start
Got to "Object Management" > "Resource Pool"

**Comment by bilalabbad** [comment]
As discussed, I'll rename every form submit button with `Save`
