### ISSUE TITLE
feature: ability to control the default group that users get added to when signing in through SSO

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4924]
### Component

API Server / GraphQL

### Describe the Feature Request

We want to have the ability to set the default group that users are added to, when signing through SSO. 

### Describe the Use Case

The company IDP does not return a set of groups as part of the request to the userinfo URL during the SSO process. 
Therefor I, as an admin of the Infrahub system, have to add the users to a group after they have signed in the first time.

I would like to add users automatically to a default group and I want the capability to configure the group that will be used for this. This way I have control over the default roles and permissions that users get assigned in the Infrahub system.

**Comment by gmazoyer** [comment]
Fixed in https://github.com/opsmill/infrahub/commit/4d9518d6926fcb8aca3abacce56989b8b6774d5f
