### ISSUE TITLE
bug: Changing `content_type` on a artifact definition doesn't change `content_type` of existing related artifacts

### ISSUE THREAD

**Issue by BaptisteGi** [opsmill/infrahub#4969]
### Component

API Server / GraphQL

### Infrahub version

1.0.5

### Current Behavior

Assuming I have multiple artifacts generated, If I change the content type of my artifact definition those artifacts will still have the older one.

### Expected Behavior

I expect artifacts generated after a change in the artifact definition to have appropriate values following the change in the definition.

### Steps to Reproduce

- Get artifacts generated with content type `text/plain`
- Change the definition of content type to `application/json`
- Trigger artifact generation
- Artifact's content type is still `text/plain`

### Additional Information

I have a repo that I can share for that

**Comment by gmazoyer** [comment]
Fixed in https://github.com/opsmill/infrahub/commit/05349014943fb4a3da678184c7cc2f52ee0f4455
