### ISSUE TITLE
bug: `Cannot query field 'xxx' on type 'Query'.` message on the UI

### ISSUE THREAD

**Issue by BaptisteGi** [opsmill/infrahub#5008]
### Component

Frontend UI, API Server / GraphQL

### Infrahub version

1.0.6

### Current Behavior

I have erratic message `Cannot query field 'xxx' on type 'Query'.` when browsing the UI even tho all workers have the same version of the schema...

Impacts repository sync as well

### Expected Behavior

No errors on the front end when browsing

### Steps to Reproduce

- `invoke dev.start`
- When the terminal give you back the hand
- Spam F5 on you browser until the point it "loads"
- Then quickly shift back to the terminal and `infrahubctl schema load models/base`
- When it's loaded, head back to the browser, enjoy

**Comment by BaptisteGi** [comment]
I have a similar message (i guess similar issue?) when refreshing the page as loading schema from git integration. This is much more impacting ...

**Comment by ogenstad** [comment]
Fixed in #5044.
