### ISSUE TITLE
bug: not able to sync a git repository on Azure DevOps Services

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#5077]
### Component

Git Integration

### Infrahub version

1.0.7

### Current Behavior

It seems that we are not able to sync a git repository that is hosted on Azure DevOps Services.

After setting the environment variable `GIT_TERMINAL_PROMPT` to `0` and then creating the repository in Infrahub, you will receive this error message:

```
remote: TF401019: The Git repository with name or identifier infrahub.git does not exist or you do not have permissions for the operation you are attempting.
fatal: repository 'https://dev.azure.com/organization/project/_git/project.git/' not found
```

Infrahub automatically appends `.git` at the end of the repository URL when it is not provided. It seems that this does not work for Azure DevOps.

Cloning the repository on your pc, using the URL with `.git` appended will give you exactly the same error message. Cloning the repository on your pc, using the URL as is, works as expected.

### Expected Behavior

The repository node is successfully created.

### Steps to Reproduce

- create a project under an organization in Azure DevOps
- create the repository as a CoreRepository in Infrahub

**Comment by ogenstad** [comment]
Fixed in #5078.
