### ISSUE TITLE
bug: menu shows up empty after access-token has expired 

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#5099]
### Component

Frontend UI

### Infrahub version

1.0.7

### Current Behavior

The menu in the frontend seems to show up empty, when you have Infrahub open in a tab in the browser, you don't use the application for a while, then come back to it and start navigating to some other page.

![image]([https://github.com/user-attachments/assets/933fe4e7-b724-4c96-8371-0269d29efa6f|https://github.com/user-attachments/assets/933fe4e7-b724-4c96-8371-0269d29efa6f])

In the console above we can see that it reports to requests that received a HTTP 401 response.

Likely the access-token had expired and after renewing it we didn't properly reload the menu?

Refreshing the page, resolves the issue

### Expected Behavior

The menu should populated at all times

### Steps to Reproduce

* spin up an instance of Infrahub
* open the frontend, login and leave the tab open for a bit more than an hour, while not using it
* navigate to some other page in the UI

**Comment by bilalabbad** [comment]
fix merged
