### ISSUE TITLE
bug: lost storage for git repositories breaks task workers

### ISSUE THREAD

**Issue by fatih-acar** [opsmill/infrahub#5109]
### Component

API Server / GraphQL

### Infrahub version

1.0.7

### Current Behavior

If we delete the contents of the task worker's disk (containing git repositories), tasks depending on the git repository fail with "No such file or directory errors" due to the repository being absent from the file system.

### Expected Behavior

I'd expect the task workers to be disposable, so when the storage is empty, the task worker should be able to restore its content automatically.

### Steps to Reproduce

Import git repository containing artifacts, transforms, etc
Delete the git repository from the storage
Regenerate an artifact

**Comment by ogenstad** [comment]
This should work if the worker restarts, is this something that is not working now or was the worker not restarted after removing the storage?

I'd also wonder if it gets repaired once the repo tries to sync again the next time. But this could have changed for the upcoming 1.1.

**Comment by fatih-acar** [comment]
I was not sure if https://github.com/opsmill/infrahub/pull/4867 took care of that issue and I was lazy enough to not retry using the latest 1.1 branch...

I will give it a try now.

**Comment by fatih-acar** [comment]
You're right @ogenstad, the issue is solved in 1.1, this is great! :smile: 

I changed the report's version to 1.0 since the issue existed there.

**Comment by ogenstad** [comment]
Ok, but did you restart the worker in 1.x after removing the storage? That part should still work. Just wondering if something might have been different in your case.
