### ISSUE TITLE
bug: CoreAccountRole and CoreObjectPermission should be branch agnostic nodes

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#5110]
# 
## 

# 
## 
### Infrahub version

1.0.7

# 
## 
### Current Behavior

When you create/modify/delete an account role in the main branch, then this change is not reflected in other existing branches in Infrahub.

When you create/modify/delete an object permission in the main branch, then this change is not reflected in other existing branches in Infrahub.

# 
## 
### Expected Behavior

create/modify/delete actions on a CoreAccountRole should be reflected in all branches

create/modify/delete actions on a CoreObjectPermission should be reflected in all branches

# 
## 
### Steps to Reproduce

* spin up instance of Infrahub
* create a new account group
* create a new branch
* switch back to the main branch
* add a new role
* assign it to the newly created group
* add an object permission for a BuiltinTag
* switch to the newly created branch
* the role will not exist in the branch
* rebase the branch
* the role now exists in the branch

# 
##

**Comment by ogenstad** [comment]
As per what we agreed upon previously this part is working as intended, the problematic part would be that queries for permissions should run in non isolation mode. I.e. a query on a branch should include updated permissions from the main branch. (similar to the auto rebase feature we had previously)

**Comment by ogenstad** [comment]
I think this is what we want instead: #5121
