### ISSUE TITLE
bug: InfrahubTask entries show the wrong related node in the frontend

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#5118]
### Component

Frontend UI

### Infrahub version

1.0.7

### Current Behavior

When you create (or delete) a new branch, then the Infrahub task entry seems to be related to the wrong user in the frontend. The user seems to be the first CoreAccount returned by the GraphQL CoreAccount query (alphabetical order).

The `related_node` of the InfrahubTask returned by the InfrahubTask GraphQL query is the correct id of the correct CoreAccount.

### Expected Behavior

An Infrahub Task should show the correct related node in the frontend.

### Steps to Reproduce

* spin up instance of Infrahub
* login as the admin user
* create a new branch
* navigate to the InfrahubTask list view
* the task to create the branch shows the correct related node "Admin"
* create a new CoreAccount "abc" (any name alphabetically ordered before Admin will do)
* navigate to the InfrahubTask list view
* the task to create the branch shows the wrong related node, the newly create CoreAccount
* execute the following GraphQL query
```graphql
query {
  InfrahubTask {
    edges {
      node {
        title
        related_node
      }
    }
  }
}
```
* the related node should be the id of the Admin user

**Comment by BeArchiTek** [comment]
Maybe similar to https://github.com/opsmill/infrahub/issues/5002
